from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _money(value):
    return f"{value:.2f}"


def _section_table(title, rows, total_label, total_value, styles):
    table_rows = [["Field", "Amount"]]
    table_rows.extend([[row["label"], _money(row["total"])] for row in rows])
    table_rows.append([total_label, _money(total_value)])

    table = Table(table_rows, colWidths=[115 * mm, 45 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#17324d")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c4cfdb")),
                ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e6eef5")),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    return [Paragraph(title, styles["Heading2"]), table, Spacer(1, 10)]


def build_accounting_range_pdf(*, buffer, report, branch_label, date_from, date_to, generated_by):
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    subtitle_style = ParagraphStyle(
        "RangeSubtitle",
        parent=styles["BodyText"],
        textColor=colors.HexColor("#556678"),
        fontSize=10,
        spaceAfter=4,
    )

    story = [
        Paragraph("Accounting Range Report", styles["Title"]),
        Spacer(1, 8),
        Paragraph(f"Branch: {branch_label}", subtitle_style),
        Paragraph(f"Date Range: {date_from:%Y-%m-%d} to {date_to:%Y-%m-%d}", subtitle_style),
        Paragraph(f"Total Summaries: {report['summary_count']}", subtitle_style),
        Paragraph(f"Generated By: {generated_by}", subtitle_style),
        Spacer(1, 10),
    ]

    overview_rows = [
        ["System Sale", _money(report["sales"]["system_sale"])],
        ["Counter Sale", _money(report["sales"]["counter_sale"])],
        ["Total Sale", _money(report["sales"]["total_sale"])],
        ["Total Purchase", _money(report["sales"]["total_purchase"])],
        ["Total Balance", _money(report["balance"])],
    ]
    overview_table = Table([["Overview", "Amount"]] + overview_rows, colWidths=[115 * mm, 45 * mm], repeatRows=1)
    overview_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#17324d")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c4cfdb")),
                ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#f7d9cb")),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ALIGN", (1, 1), (1, -1), "RIGHT"),
            ]
        )
    )
    story.extend([Paragraph("Range Overview", styles["Heading2"]), overview_table, Spacer(1, 10)])

    for section in report["sections"]:
        story.extend(
            _section_table(
                section["title"],
                section["breakdown"],
                section["total_label"],
                section["total"],
                styles,
            )
        )

    document.build(story)


def build_sheikh_bill_pdf(*, buffer, rows, branch_label, date_from, date_to, generated_by):
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )
    styles = getSampleStyleSheet()
    subtitle_style = ParagraphStyle(
        "SheikhBillSubtitle",
        parent=styles["BodyText"],
        textColor=colors.HexColor("#556678"),
        fontSize=10,
        spaceAfter=4,
    )
    total = sum((row["amount"] for row in rows), 0)
    table_rows = [["Date", "Branch", "Reference", "Sheikh Bill"]]
    table_rows.extend(
        [
            row["summary"].sheet_date.strftime("%Y-%m-%d"),
            row["summary"].branch.name if row["summary"].branch else "Unassigned",
            row["summary"].reference_number,
            _money(row["amount"]),
        ]
        for row in rows
    )
    table_rows.append(["", "", "Total Sheikh Bill", _money(total)])

    table = Table(table_rows, colWidths=[30 * mm, 48 * mm, 50 * mm, 32 * mm], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#17324d")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#c4cfdb")),
                ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e6eef5")),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    story = [
        Paragraph("Sheikh Bill Date-wise Report", styles["Title"]),
        Spacer(1, 8),
        Paragraph(f"Branch: {branch_label}", subtitle_style),
        Paragraph(f"Date Range: {date_from:%Y-%m-%d} to {date_to:%Y-%m-%d}", subtitle_style),
        Paragraph(f"Entries: {len(rows)}", subtitle_style),
        Paragraph(f"Generated By: {generated_by}", subtitle_style),
        Spacer(1, 10),
        table,
    ]
    document.build(story)
