# Generated by Django 6.0.3 on 2026-03-26 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('warehouse_name', models.CharField(max_length=150)),
                ('sheet_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sheet_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.stocksheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
