# Generated by Django 6.0.3 on 2026-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksheet',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stocksheet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stocksheet',
            name='warehouse_name',
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='counter_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='local_purchases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='market_purchases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='system_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='total_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='totals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
