# Generated by Django 6.0.3 on 2026-03-27 10:37

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_ITEM_NAMES = [
    "Chicken Thigh Fillet",
    "Chicken Patty",
    "Chicken Nuggets",
    "Chicken Wings",
    "Chicken Piece",
    "Small Dough",
    "Medium Dough",
    "Large Dough",
    "Burger Buns",
    "Paratha / Bread",
    "Tortia Wrap",
    "Sandwich Bread",
    "Veggie Burger",
    "Eggs",
    "Coke 0.5L",
    "Coke 1L",
    "Coke 1.5L",
    "Coke 350L",
    "Fish Fillet",
    "Kabab",
    "Tikka",
    "Malai Boti",
    "Chargha",
]


def seed_defaults(apps, schema_editor):
    Branch = apps.get_model("stocks", "Branch")
    Item = apps.get_model("stocks", "Item")

    Branch.objects.get_or_create(name="Barki Road")
    Branch.objects.get_or_create(name="Bediyan Road")
    for item_name in DEFAULT_ITEM_NAMES:
        Item.objects.get_or_create(name=item_name)


def remove_defaults(apps, schema_editor):
    Branch = apps.get_model("stocks", "Branch")
    Item = apps.get_model("stocks", "Item")

    Branch.objects.filter(name__in=["Barki Road", "Bediyan Road"]).delete()
    Item.objects.filter(name__in=DEFAULT_ITEM_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stocksheet_notes_remove_stocksheet_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='stocks.branch')),
            ],
            options={
                'ordering': ['-date', 'branch__name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
                ('cancelled', models.IntegerField(default=0)),
                ('exchange', models.IntegerField(default=0)),
                ('ready', models.IntegerField(default=0)),
                ('daily_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stocks.dailystock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='stocks.item')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.DeleteModel(
            name='StockSheet',
        ),
        migrations.AddConstraint(
            model_name='dailystock',
            constraint=models.UniqueConstraint(fields=('date', 'branch'), name='unique_daily_stock_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.UniqueConstraint(fields=('daily_stock', 'item'), name='unique_entry_per_item_per_daily_stock'),
        ),
        migrations.RunPython(seed_defaults, remove_defaults),
    ]
