# Generated by Django 6.0.3 on 2026-03-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_branch_item_dailystock_stockentry_delete_stocksheet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('sheet_date', models.DateField()),
                ('system_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local_purchases', models.JSONField(blank=True, default=dict)),
                ('market_purchases', models.JSONField(blank=True, default=dict)),
                ('counter_summary', models.JSONField(blank=True, default=dict)),
                ('total_summary', models.JSONField(blank=True, default=dict)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sheet_date', '-created_at'],
            },
        ),
    ]
