# Generated by Django 6.0.3 on 2026-03-27 10:54

from django.db import migrations, models


def seed_branches(apps, schema_editor):
    Branch = apps.get_model("stocks", "Branch")
    Branch.objects.get_or_create(name="Barki Road")
    Branch.objects.get_or_create(name="Bediyan Road")


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stocksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='food_panda_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='shop_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(seed_branches, migrations.RunPython.noop),
    ]
