# Generated by Django 6.0.3 on 2026-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_seed_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='in_hand',
            field=models.IntegerField(default=0),
        ),
    ]
