# Generated by Django 6.0.3 on 2026-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stockentry_in_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
