# Generated by Django 6.0.3 on 2026-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockentry_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='remaining_value',
            field=models.IntegerField(default=0),
        ),
    ]
