# Generated by Django 6.0.3 on 2026-03-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_stockentry_remaining_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksheet',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_summaries', to='stocks.branch'),
        ),
    ]
