# Generated by Django 6.0.3 on 2026-03-27 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_stocksheet_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocksheet',
            constraint=models.UniqueConstraint(fields=('sheet_date', 'branch'), name='unique_account_summary_per_branch_per_day'),
        ),
    ]
