# Generated by Django 6.0.3 on 2026-05-09 09:49

import django.db.models.deletion
from django.db import migrations, models


def clear_entries_using_stock_sheet_items(apps, schema_editor):
    StockRegisterEntry = apps.get_model("stock_register", "StockRegisterEntry")
    StockRegisterEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(clear_entries_using_stock_sheet_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockregisterentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock_register.stockregisteritem'),
        ),
    ]
