# Generated by Django 6.0.3 on 2026-05-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0002_stockregisteritem_alter_stockregisterentry_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockregisterentry',
            name='stock_in_hand',
        ),
    ]
