# Generated by Django 6.0.3 on 2026-05-09 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0003_remove_stockregisterentry_stock_in_hand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockregister',
            name='unique_stock_register_per_branch',
        ),
        migrations.RemoveConstraint(
            model_name='stockregisterentry',
            name='unique_stock_register_entry_per_item',
        ),
        migrations.RemoveField(
            model_name='stockregister',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockregister',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockregister',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='stockregisterentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockregisterentry',
            name='register',
        ),
        migrations.DeleteModel(
            name='StockRegister',
        ),
        migrations.DeleteModel(
            name='StockRegisterEntry',
        ),
        migrations.RenameModel(
            old_name='StockRegisterItem',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_from', models.CharField(blank=True, max_length=255)),
                ('issued_to', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_register_transactions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stock_register.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
