# Generated by Django 6.0.3 on 2026-05-09 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_register', '0004_item_stocktransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
